# TO USE THIS FILE, RENAME IT TO "config.yml".

# HumeBots/                    ____              _ 
# | | | |_   _ _ __ ___   ___ / ___|___  _ __ __| |
# | |_| | | | | '_ ` _ \ / _ \ |   / _ \| '__/ _` |
# |  _  | |_| | | | | | |  __/ |__| (_) | | | (_| |
# |_| |_|\__,_|_| |_| |_|\___|\____\___/|_|  \__,_|
#                                               API

# This is the API configuration file for HumeCord.

# This defines the default database contents for each blueprint.
# This list is also used to tell what bots exist at all.
data:
  main:
    stats: {}
    overrides: 
      guilds: {}

  sample:
    guilds: {}


# All authentication keys.
# Keys should be passed in the "key" key of each request's JSON.
# Everything in the key's value (list) is a blueprint that this
#   key will be allowed to access.
# Ex:
#   key_value: [main, bot1, bot2]
# can access main, bot1, and bot2.
auth:
  change_this_key_its_insecure: [main, sample] # Debug (*)
  another_bad_key_you_should_change: [main, sample] # Testcord

# Whitelisted IPs.
ips:
  - "::1"
  - "localhost"
  - "127.0.0.1"

# Won't be registered to the status or ready API, probably
#   because they're not bots.
ignore_ready:
  - main

# Extra config values, referenced manually
# (using api.config.config[]).
config:
  overrides:
    defaults:
      sample: 5